/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedXpRouteImport } from './routes/_authenticated/xp'
import { Route as AuthenticatedTreinosRouteImport } from './routes/_authenticated/treinos'
import { Route as AuthenticatedTrainingPlanRouteImport } from './routes/_authenticated/training-plan'
import { Route as AuthenticatedTimerRouteImport } from './routes/_authenticated/timer'
import { Route as AuthenticatedRelatorioRouteImport } from './routes/_authenticated/relatorio'
import { Route as AuthenticatedProgressoRouteImport } from './routes/_authenticated/progresso'
import { Route as AuthenticatedPreferenciasRouteImport } from './routes/_authenticated/preferencias'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNiveisRouteImport } from './routes/_authenticated/niveis'
import { Route as AuthenticatedLembretesRouteImport } from './routes/_authenticated/lembretes'
import { Route as AuthenticatedJogadorRouteImport } from './routes/_authenticated/jogador'
import { Route as AuthenticatedFirstWorkoutRouteImport } from './routes/_authenticated/first-workout'
import { Route as AuthenticatedDietaRouteImport } from './routes/_authenticated/dieta'
import { Route as AuthenticatedConquistasRouteImport } from './routes/_authenticated/conquistas'
import { Route as AuthenticatedAssessmentRouteImport } from './routes/_authenticated/assessment'
import { Route as AuthenticatedTreinosIndexRouteImport } from './routes/_authenticated/treinos.index'
import { Route as AuthenticatedTreinosSlugRouteImport } from './routes/_authenticated/treinos.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedXpRoute = AuthenticatedXpRouteImport.update({
  id: '/xp',
  path: '/xp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreinosRoute = AuthenticatedTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrainingPlanRoute =
  AuthenticatedTrainingPlanRouteImport.update({
    id: '/training-plan',
    path: '/training-plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimerRoute = AuthenticatedTimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatorioRoute = AuthenticatedRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressoRoute = AuthenticatedProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreferenciasRoute =
  AuthenticatedPreferenciasRouteImport.update({
    id: '/preferencias',
    path: '/preferencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNiveisRoute = AuthenticatedNiveisRouteImport.update({
  id: '/niveis',
  path: '/niveis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLembretesRoute = AuthenticatedLembretesRouteImport.update({
  id: '/lembretes',
  path: '/lembretes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJogadorRoute = AuthenticatedJogadorRouteImport.update({
  id: '/jogador',
  path: '/jogador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFirstWorkoutRoute =
  AuthenticatedFirstWorkoutRouteImport.update({
    id: '/first-workout',
    path: '/first-workout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDietaRoute = AuthenticatedDietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConquistasRoute = AuthenticatedConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentRoute = AuthenticatedAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreinosIndexRoute =
  AuthenticatedTreinosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTreinosRoute,
  } as any)
const AuthenticatedTreinosSlugRoute =
  AuthenticatedTreinosSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedTreinosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/dieta': typeof AuthenticatedDietaRoute
  '/first-workout': typeof AuthenticatedFirstWorkoutRoute
  '/jogador': typeof AuthenticatedJogadorRoute
  '/lembretes': typeof AuthenticatedLembretesRoute
  '/niveis': typeof AuthenticatedNiveisRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/preferencias': typeof AuthenticatedPreferenciasRoute
  '/progresso': typeof AuthenticatedProgressoRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/timer': typeof AuthenticatedTimerRoute
  '/training-plan': typeof AuthenticatedTrainingPlanRoute
  '/treinos': typeof AuthenticatedTreinosRouteWithChildren
  '/xp': typeof AuthenticatedXpRoute
  '/treinos/$slug': typeof AuthenticatedTreinosSlugRoute
  '/treinos/': typeof AuthenticatedTreinosIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/dieta': typeof AuthenticatedDietaRoute
  '/first-workout': typeof AuthenticatedFirstWorkoutRoute
  '/jogador': typeof AuthenticatedJogadorRoute
  '/lembretes': typeof AuthenticatedLembretesRoute
  '/niveis': typeof AuthenticatedNiveisRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/preferencias': typeof AuthenticatedPreferenciasRoute
  '/progresso': typeof AuthenticatedProgressoRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/timer': typeof AuthenticatedTimerRoute
  '/training-plan': typeof AuthenticatedTrainingPlanRoute
  '/xp': typeof AuthenticatedXpRoute
  '/': typeof AuthenticatedIndexRoute
  '/treinos/$slug': typeof AuthenticatedTreinosSlugRoute
  '/treinos': typeof AuthenticatedTreinosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assessment': typeof AuthenticatedAssessmentRoute
  '/_authenticated/conquistas': typeof AuthenticatedConquistasRoute
  '/_authenticated/dieta': typeof AuthenticatedDietaRoute
  '/_authenticated/first-workout': typeof AuthenticatedFirstWorkoutRoute
  '/_authenticated/jogador': typeof AuthenticatedJogadorRoute
  '/_authenticated/lembretes': typeof AuthenticatedLembretesRoute
  '/_authenticated/niveis': typeof AuthenticatedNiveisRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/preferencias': typeof AuthenticatedPreferenciasRoute
  '/_authenticated/progresso': typeof AuthenticatedProgressoRoute
  '/_authenticated/relatorio': typeof AuthenticatedRelatorioRoute
  '/_authenticated/timer': typeof AuthenticatedTimerRoute
  '/_authenticated/training-plan': typeof AuthenticatedTrainingPlanRoute
  '/_authenticated/treinos': typeof AuthenticatedTreinosRouteWithChildren
  '/_authenticated/xp': typeof AuthenticatedXpRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/treinos/$slug': typeof AuthenticatedTreinosSlugRoute
  '/_authenticated/treinos/': typeof AuthenticatedTreinosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assessment'
    | '/conquistas'
    | '/dieta'
    | '/first-workout'
    | '/jogador'
    | '/lembretes'
    | '/niveis'
    | '/onboarding'
    | '/perfil'
    | '/preferencias'
    | '/progresso'
    | '/relatorio'
    | '/timer'
    | '/training-plan'
    | '/treinos'
    | '/xp'
    | '/treinos/$slug'
    | '/treinos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/assessment'
    | '/conquistas'
    | '/dieta'
    | '/first-workout'
    | '/jogador'
    | '/lembretes'
    | '/niveis'
    | '/onboarding'
    | '/perfil'
    | '/preferencias'
    | '/progresso'
    | '/relatorio'
    | '/timer'
    | '/training-plan'
    | '/xp'
    | '/'
    | '/treinos/$slug'
    | '/treinos'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assessment'
    | '/_authenticated/conquistas'
    | '/_authenticated/dieta'
    | '/_authenticated/first-workout'
    | '/_authenticated/jogador'
    | '/_authenticated/lembretes'
    | '/_authenticated/niveis'
    | '/_authenticated/onboarding'
    | '/_authenticated/perfil'
    | '/_authenticated/preferencias'
    | '/_authenticated/progresso'
    | '/_authenticated/relatorio'
    | '/_authenticated/timer'
    | '/_authenticated/training-plan'
    | '/_authenticated/treinos'
    | '/_authenticated/xp'
    | '/_authenticated/'
    | '/_authenticated/treinos/$slug'
    | '/_authenticated/treinos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/xp': {
      id: '/_authenticated/xp'
      path: '/xp'
      fullPath: '/xp'
      preLoaderRoute: typeof AuthenticatedXpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treinos': {
      id: '/_authenticated/treinos'
      path: '/treinos'
      fullPath: '/treinos'
      preLoaderRoute: typeof AuthenticatedTreinosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training-plan': {
      id: '/_authenticated/training-plan'
      path: '/training-plan'
      fullPath: '/training-plan'
      preLoaderRoute: typeof AuthenticatedTrainingPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timer': {
      id: '/_authenticated/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof AuthenticatedTimerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio': {
      id: '/_authenticated/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AuthenticatedRelatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progresso': {
      id: '/_authenticated/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof AuthenticatedProgressoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preferencias': {
      id: '/_authenticated/preferencias'
      path: '/preferencias'
      fullPath: '/preferencias'
      preLoaderRoute: typeof AuthenticatedPreferenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/niveis': {
      id: '/_authenticated/niveis'
      path: '/niveis'
      fullPath: '/niveis'
      preLoaderRoute: typeof AuthenticatedNiveisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lembretes': {
      id: '/_authenticated/lembretes'
      path: '/lembretes'
      fullPath: '/lembretes'
      preLoaderRoute: typeof AuthenticatedLembretesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jogador': {
      id: '/_authenticated/jogador'
      path: '/jogador'
      fullPath: '/jogador'
      preLoaderRoute: typeof AuthenticatedJogadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/first-workout': {
      id: '/_authenticated/first-workout'
      path: '/first-workout'
      fullPath: '/first-workout'
      preLoaderRoute: typeof AuthenticatedFirstWorkoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dieta': {
      id: '/_authenticated/dieta'
      path: '/dieta'
      fullPath: '/dieta'
      preLoaderRoute: typeof AuthenticatedDietaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conquistas': {
      id: '/_authenticated/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof AuthenticatedConquistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment': {
      id: '/_authenticated/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AuthenticatedAssessmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treinos/': {
      id: '/_authenticated/treinos/'
      path: '/'
      fullPath: '/treinos/'
      preLoaderRoute: typeof AuthenticatedTreinosIndexRouteImport
      parentRoute: typeof AuthenticatedTreinosRoute
    }
    '/_authenticated/treinos/$slug': {
      id: '/_authenticated/treinos/$slug'
      path: '/$slug'
      fullPath: '/treinos/$slug'
      preLoaderRoute: typeof AuthenticatedTreinosSlugRouteImport
      parentRoute: typeof AuthenticatedTreinosRoute
    }
  }
}

interface AuthenticatedTreinosRouteChildren {
  AuthenticatedTreinosSlugRoute: typeof AuthenticatedTreinosSlugRoute
  AuthenticatedTreinosIndexRoute: typeof AuthenticatedTreinosIndexRoute
}

const AuthenticatedTreinosRouteChildren: AuthenticatedTreinosRouteChildren = {
  AuthenticatedTreinosSlugRoute: AuthenticatedTreinosSlugRoute,
  AuthenticatedTreinosIndexRoute: AuthenticatedTreinosIndexRoute,
}

const AuthenticatedTreinosRouteWithChildren =
  AuthenticatedTreinosRoute._addFileChildren(AuthenticatedTreinosRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssessmentRoute: typeof AuthenticatedAssessmentRoute
  AuthenticatedConquistasRoute: typeof AuthenticatedConquistasRoute
  AuthenticatedDietaRoute: typeof AuthenticatedDietaRoute
  AuthenticatedFirstWorkoutRoute: typeof AuthenticatedFirstWorkoutRoute
  AuthenticatedJogadorRoute: typeof AuthenticatedJogadorRoute
  AuthenticatedLembretesRoute: typeof AuthenticatedLembretesRoute
  AuthenticatedNiveisRoute: typeof AuthenticatedNiveisRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPreferenciasRoute: typeof AuthenticatedPreferenciasRoute
  AuthenticatedProgressoRoute: typeof AuthenticatedProgressoRoute
  AuthenticatedRelatorioRoute: typeof AuthenticatedRelatorioRoute
  AuthenticatedTimerRoute: typeof AuthenticatedTimerRoute
  AuthenticatedTrainingPlanRoute: typeof AuthenticatedTrainingPlanRoute
  AuthenticatedTreinosRoute: typeof AuthenticatedTreinosRouteWithChildren
  AuthenticatedXpRoute: typeof AuthenticatedXpRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssessmentRoute: AuthenticatedAssessmentRoute,
  AuthenticatedConquistasRoute: AuthenticatedConquistasRoute,
  AuthenticatedDietaRoute: AuthenticatedDietaRoute,
  AuthenticatedFirstWorkoutRoute: AuthenticatedFirstWorkoutRoute,
  AuthenticatedJogadorRoute: AuthenticatedJogadorRoute,
  AuthenticatedLembretesRoute: AuthenticatedLembretesRoute,
  AuthenticatedNiveisRoute: AuthenticatedNiveisRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPreferenciasRoute: AuthenticatedPreferenciasRoute,
  AuthenticatedProgressoRoute: AuthenticatedProgressoRoute,
  AuthenticatedRelatorioRoute: AuthenticatedRelatorioRoute,
  AuthenticatedTimerRoute: AuthenticatedTimerRoute,
  AuthenticatedTrainingPlanRoute: AuthenticatedTrainingPlanRoute,
  AuthenticatedTreinosRoute: AuthenticatedTreinosRouteWithChildren,
  AuthenticatedXpRoute: AuthenticatedXpRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
