/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreinosRouteImport } from './routes/treinos'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as ProgressoRouteImport } from './routes/progresso'
import { Route as PreferenciasRouteImport } from './routes/preferencias'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as DietaRouteImport } from './routes/dieta'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreinosIndexRouteImport } from './routes/treinos.index'
import { Route as TreinosSlugRouteImport } from './routes/treinos.$slug'

const TreinosRoute = TreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => rootRouteImport,
} as any)
const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressoRoute = ProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferenciasRoute = PreferenciasRouteImport.update({
  id: '/preferencias',
  path: '/preferencias',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const DietaRoute = DietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinosIndexRoute = TreinosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TreinosRoute,
} as any)
const TreinosSlugRoute = TreinosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TreinosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dieta': typeof DietaRoute
  '/perfil': typeof PerfilRoute
  '/preferencias': typeof PreferenciasRoute
  '/progresso': typeof ProgressoRoute
  '/relatorio': typeof RelatorioRoute
  '/timer': typeof TimerRoute
  '/treinos': typeof TreinosRouteWithChildren
  '/treinos/$slug': typeof TreinosSlugRoute
  '/treinos/': typeof TreinosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dieta': typeof DietaRoute
  '/perfil': typeof PerfilRoute
  '/preferencias': typeof PreferenciasRoute
  '/progresso': typeof ProgressoRoute
  '/relatorio': typeof RelatorioRoute
  '/timer': typeof TimerRoute
  '/treinos/$slug': typeof TreinosSlugRoute
  '/treinos': typeof TreinosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dieta': typeof DietaRoute
  '/perfil': typeof PerfilRoute
  '/preferencias': typeof PreferenciasRoute
  '/progresso': typeof ProgressoRoute
  '/relatorio': typeof RelatorioRoute
  '/timer': typeof TimerRoute
  '/treinos': typeof TreinosRouteWithChildren
  '/treinos/$slug': typeof TreinosSlugRoute
  '/treinos/': typeof TreinosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dieta'
    | '/perfil'
    | '/preferencias'
    | '/progresso'
    | '/relatorio'
    | '/timer'
    | '/treinos'
    | '/treinos/$slug'
    | '/treinos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dieta'
    | '/perfil'
    | '/preferencias'
    | '/progresso'
    | '/relatorio'
    | '/timer'
    | '/treinos/$slug'
    | '/treinos'
  id:
    | '__root__'
    | '/'
    | '/dieta'
    | '/perfil'
    | '/preferencias'
    | '/progresso'
    | '/relatorio'
    | '/timer'
    | '/treinos'
    | '/treinos/$slug'
    | '/treinos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DietaRoute: typeof DietaRoute
  PerfilRoute: typeof PerfilRoute
  PreferenciasRoute: typeof PreferenciasRoute
  ProgressoRoute: typeof ProgressoRoute
  RelatorioRoute: typeof RelatorioRoute
  TimerRoute: typeof TimerRoute
  TreinosRoute: typeof TreinosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treinos': {
      id: '/treinos'
      path: '/treinos'
      fullPath: '/treinos'
      preLoaderRoute: typeof TreinosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progresso': {
      id: '/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof ProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferencias': {
      id: '/preferencias'
      path: '/preferencias'
      fullPath: '/preferencias'
      preLoaderRoute: typeof PreferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieta': {
      id: '/dieta'
      path: '/dieta'
      fullPath: '/dieta'
      preLoaderRoute: typeof DietaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinos/': {
      id: '/treinos/'
      path: '/'
      fullPath: '/treinos/'
      preLoaderRoute: typeof TreinosIndexRouteImport
      parentRoute: typeof TreinosRoute
    }
    '/treinos/$slug': {
      id: '/treinos/$slug'
      path: '/$slug'
      fullPath: '/treinos/$slug'
      preLoaderRoute: typeof TreinosSlugRouteImport
      parentRoute: typeof TreinosRoute
    }
  }
}

interface TreinosRouteChildren {
  TreinosSlugRoute: typeof TreinosSlugRoute
  TreinosIndexRoute: typeof TreinosIndexRoute
}

const TreinosRouteChildren: TreinosRouteChildren = {
  TreinosSlugRoute: TreinosSlugRoute,
  TreinosIndexRoute: TreinosIndexRoute,
}

const TreinosRouteWithChildren =
  TreinosRoute._addFileChildren(TreinosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DietaRoute: DietaRoute,
  PerfilRoute: PerfilRoute,
  PreferenciasRoute: PreferenciasRoute,
  ProgressoRoute: ProgressoRoute,
  RelatorioRoute: RelatorioRoute,
  TimerRoute: TimerRoute,
  TreinosRoute: TreinosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
