/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTreinosRouteImport } from './routes/_authenticated/treinos'
import { Route as AuthenticatedTimerRouteImport } from './routes/_authenticated/timer'
import { Route as AuthenticatedRelatorioRouteImport } from './routes/_authenticated/relatorio'
import { Route as AuthenticatedProgressoRouteImport } from './routes/_authenticated/progresso'
import { Route as AuthenticatedPreferenciasRouteImport } from './routes/_authenticated/preferencias'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLembretesRouteImport } from './routes/_authenticated/lembretes'
import { Route as AuthenticatedDietaRouteImport } from './routes/_authenticated/dieta'
import { Route as AuthenticatedTreinosIndexRouteImport } from './routes/_authenticated/treinos.index'
import { Route as AuthenticatedTreinosSlugRouteImport } from './routes/_authenticated/treinos.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreinosRoute = AuthenticatedTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimerRoute = AuthenticatedTimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatorioRoute = AuthenticatedRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressoRoute = AuthenticatedProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreferenciasRoute =
  AuthenticatedPreferenciasRouteImport.update({
    id: '/preferencias',
    path: '/preferencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLembretesRoute = AuthenticatedLembretesRouteImport.update({
  id: '/lembretes',
  path: '/lembretes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDietaRoute = AuthenticatedDietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreinosIndexRoute =
  AuthenticatedTreinosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTreinosRoute,
  } as any)
const AuthenticatedTreinosSlugRoute =
  AuthenticatedTreinosSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedTreinosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/dieta': typeof AuthenticatedDietaRoute
  '/lembretes': typeof AuthenticatedLembretesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/preferencias': typeof AuthenticatedPreferenciasRoute
  '/progresso': typeof AuthenticatedProgressoRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/timer': typeof AuthenticatedTimerRoute
  '/treinos': typeof AuthenticatedTreinosRouteWithChildren
  '/treinos/$slug': typeof AuthenticatedTreinosSlugRoute
  '/treinos/': typeof AuthenticatedTreinosIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/dieta': typeof AuthenticatedDietaRoute
  '/lembretes': typeof AuthenticatedLembretesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/preferencias': typeof AuthenticatedPreferenciasRoute
  '/progresso': typeof AuthenticatedProgressoRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/timer': typeof AuthenticatedTimerRoute
  '/': typeof AuthenticatedIndexRoute
  '/treinos/$slug': typeof AuthenticatedTreinosSlugRoute
  '/treinos': typeof AuthenticatedTreinosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dieta': typeof AuthenticatedDietaRoute
  '/_authenticated/lembretes': typeof AuthenticatedLembretesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/preferencias': typeof AuthenticatedPreferenciasRoute
  '/_authenticated/progresso': typeof AuthenticatedProgressoRoute
  '/_authenticated/relatorio': typeof AuthenticatedRelatorioRoute
  '/_authenticated/timer': typeof AuthenticatedTimerRoute
  '/_authenticated/treinos': typeof AuthenticatedTreinosRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/treinos/$slug': typeof AuthenticatedTreinosSlugRoute
  '/_authenticated/treinos/': typeof AuthenticatedTreinosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dieta'
    | '/lembretes'
    | '/onboarding'
    | '/perfil'
    | '/preferencias'
    | '/progresso'
    | '/relatorio'
    | '/timer'
    | '/treinos'
    | '/treinos/$slug'
    | '/treinos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/dieta'
    | '/lembretes'
    | '/onboarding'
    | '/perfil'
    | '/preferencias'
    | '/progresso'
    | '/relatorio'
    | '/timer'
    | '/'
    | '/treinos/$slug'
    | '/treinos'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dieta'
    | '/_authenticated/lembretes'
    | '/_authenticated/onboarding'
    | '/_authenticated/perfil'
    | '/_authenticated/preferencias'
    | '/_authenticated/progresso'
    | '/_authenticated/relatorio'
    | '/_authenticated/timer'
    | '/_authenticated/treinos'
    | '/_authenticated/'
    | '/_authenticated/treinos/$slug'
    | '/_authenticated/treinos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treinos': {
      id: '/_authenticated/treinos'
      path: '/treinos'
      fullPath: '/treinos'
      preLoaderRoute: typeof AuthenticatedTreinosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timer': {
      id: '/_authenticated/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof AuthenticatedTimerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio': {
      id: '/_authenticated/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AuthenticatedRelatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progresso': {
      id: '/_authenticated/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof AuthenticatedProgressoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preferencias': {
      id: '/_authenticated/preferencias'
      path: '/preferencias'
      fullPath: '/preferencias'
      preLoaderRoute: typeof AuthenticatedPreferenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lembretes': {
      id: '/_authenticated/lembretes'
      path: '/lembretes'
      fullPath: '/lembretes'
      preLoaderRoute: typeof AuthenticatedLembretesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dieta': {
      id: '/_authenticated/dieta'
      path: '/dieta'
      fullPath: '/dieta'
      preLoaderRoute: typeof AuthenticatedDietaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treinos/': {
      id: '/_authenticated/treinos/'
      path: '/'
      fullPath: '/treinos/'
      preLoaderRoute: typeof AuthenticatedTreinosIndexRouteImport
      parentRoute: typeof AuthenticatedTreinosRoute
    }
    '/_authenticated/treinos/$slug': {
      id: '/_authenticated/treinos/$slug'
      path: '/$slug'
      fullPath: '/treinos/$slug'
      preLoaderRoute: typeof AuthenticatedTreinosSlugRouteImport
      parentRoute: typeof AuthenticatedTreinosRoute
    }
  }
}

interface AuthenticatedTreinosRouteChildren {
  AuthenticatedTreinosSlugRoute: typeof AuthenticatedTreinosSlugRoute
  AuthenticatedTreinosIndexRoute: typeof AuthenticatedTreinosIndexRoute
}

const AuthenticatedTreinosRouteChildren: AuthenticatedTreinosRouteChildren = {
  AuthenticatedTreinosSlugRoute: AuthenticatedTreinosSlugRoute,
  AuthenticatedTreinosIndexRoute: AuthenticatedTreinosIndexRoute,
}

const AuthenticatedTreinosRouteWithChildren =
  AuthenticatedTreinosRoute._addFileChildren(AuthenticatedTreinosRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDietaRoute: typeof AuthenticatedDietaRoute
  AuthenticatedLembretesRoute: typeof AuthenticatedLembretesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPreferenciasRoute: typeof AuthenticatedPreferenciasRoute
  AuthenticatedProgressoRoute: typeof AuthenticatedProgressoRoute
  AuthenticatedRelatorioRoute: typeof AuthenticatedRelatorioRoute
  AuthenticatedTimerRoute: typeof AuthenticatedTimerRoute
  AuthenticatedTreinosRoute: typeof AuthenticatedTreinosRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDietaRoute: AuthenticatedDietaRoute,
  AuthenticatedLembretesRoute: AuthenticatedLembretesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPreferenciasRoute: AuthenticatedPreferenciasRoute,
  AuthenticatedProgressoRoute: AuthenticatedProgressoRoute,
  AuthenticatedRelatorioRoute: AuthenticatedRelatorioRoute,
  AuthenticatedTimerRoute: AuthenticatedTimerRoute,
  AuthenticatedTreinosRoute: AuthenticatedTreinosRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
